author: vemacs
database: false
description: Simple chat manager for Bukkit
generator: http://dinnerbone.com/minecraft/tools/pluginator/
main: com.nullblock.vemacs.plugins.simplecm.SimpleCM
name: SimpleCM
startup: postworld
url: http://github.com/vemacs/SimpleCM
version: '1.0'
